### ISSUE TITLE
Allow optionally working on video frames in-memory

### ISSUE THREAD

**Issue by Firepal** [ArdenButterfield/stammer#11]
This project works very well, but it temporarily uses a lot of disk space. `ffmpeg` can write all images of a video to pipe, which Python can read. It's then possible to build output frames in memory too. 

As computers today have many GBs of memory, this could save `ffmpeg` the trouble of unnecessarily writing image files which will be soon deleted anyway.

I have a fork of this at home which does the read-into-memory, but as of writing, not the output-building.

Thoughts?

**Comment by Firepal** [comment]
I am already working on this, if you are interested feel free to assign me this issue

**Comment by ArdenButterfield** [comment]
Thanks for getting on that! This was definitely on my back-burner to-do list, I would be happy to help out. I imagine the most pythonic way to do this would be to pass the ffmpeg wav output into a bytesIO object, which we can read with wavfile.read().

**Comment by Firepal** [comment]
I was gonna do this for video frames, but I might do this for audio first... 
WAVs are not so big as thousands of video frames :)

**Comment by mayhair** [comment]
I agree that it will save a lot of disk space and allow faster writing of the frames.
One of the reasons you said to use it is because modern computers have plenty of RAM. This makes sense for short videos such as "Steamed Hams". However, it makes less sense for longer ones.
For example, I made a [video](https://www.youtube.com/watch?v=yehGuaevY5w) with this script from a ~2.5 GB 720p copy of "Bee Movie". Uncompressed and lossless image/video formats take up a lot of space, and even with the frames being in the compressed PNG format, the frames totalled around 126 GB (127 GB on disk). For perspective, the computer with which I generated the video has 32 GB of RAM.

How will this problem be addressed? I suspect that a mix of using the actual RAM and writing to disk (maybe via a page file?) could be used. I also believe that once the frames needed to build the video are chosen, the useless ones can be immediately deleted before the build starts.

**Comment by Firepal** [comment]
> How will this problem be addressed? I suspect that a mix of using the actual RAM and writing to disk (maybe via a page file?) could be used. 


>I also believe that once the frames needed to build the video are chosen, the useless ones can be immediately deleted before the build starts.

This gives me an idea: 
How about we continuously decode the carrier video's frames into a "cache" which decays over x frames?

All newly-used or reused frames would have a "frame timer" set to a constant, say 500.
Every processed output frame, we decrement all timers by one. 
When a frame's timer reaches zero, we could either:
- Delete the frame, and re-decode the frame from the video when it needs to be reused
- Write the frame in base64 to a file (which could contain a list of many of these frames), and read it when needed.

On top of this, we should be able to directly pipe these sorted frames into FFmpeg without having the temporary "outframes" PNG list. This would be a memory gain, because the modulator is often much shorter than the carrier.

**Comment by Firepal** [comment]
Also, 8-bit PNGs are smaller but look just as good. Might even go for JPEG compression as an option.

**Comment by ArdenButterfield** [comment]
yeah, saving the images in a smaller format definitely makes sense! Especially since YouTube compression loves to obliterate these videos since there's so much changing from frame to frame.... No need to work in high quality for it to just be lost later on.

**Comment by Firepal** [comment]
I have a working POC that, on 720p carrier video, averages 300-600MB of RAM usage without a single image file written to disk. 

looks to initially run at about 5fps and progressively gets more bursts of speed as more frames get cached, avg. 25fps.
![image](https://user-images.githubusercontent.com/29317321/226483479-2751c234-7329-4fe9-80bc-cea3e5f83e0b.png)

**Comment by Firepal** [comment]
It's a spaghetti mess, but it is working nicely. Haven't tried it with a movie yet.

I think I messed up the branch's history, I made this on an older version of the code. eh will figure it out later.
https://github.com/Firepal/stammer/tree/video_in_mem

**Comment by Firepal** [comment]
Hmm. On a 1hour video, the "analyzing audio" part is very taxing on my 16GB of RAM.
